# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:14.
BEGIN attributes
  NAMES  pw_113
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
    2343.00000000      -0.02894578
    2586.00000000      -0.02894578
END timeseries

