# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_176
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000      -0.00000000
    1096.00000000      -0.01676184
    1461.00000000      -0.45645287
    1652.00000000      -0.00000000
    2385.00000000      -0.06224781
    2557.00000000      -0.41875907
    2586.00000000      -0.41875907
END timeseries

