# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_75
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
    2192.00000000     -10.76673455
    2557.00000000   -1100.20570276
    2586.00000000   -1100.20570276
END timeseries

