# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_91
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000      -0.00000000
    2192.00000000      -2.38692669
    2586.00000000      -2.38692669
END timeseries

