# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_1
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
    1704.00000000      -0.09857212
    2586.00000000      -0.09857212
END timeseries

