# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:14.
BEGIN attributes
  NAMES  pw_148
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
     243.00000000      -3.44345286
     273.00000000      -3.79040856
     304.00000000      -2.51718782
    2586.00000000      -2.51718782
END timeseries

