# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_235
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
    1704.00000000     -39.42884949
    1826.00000000      -0.01801856
    2586.00000000      -0.01801856
END timeseries

