# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_50
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
     365.00000000      -0.00000000
     425.00000000      -0.12113318
     456.00000000      -0.00000000
    2586.00000000      -0.00000000
END timeseries

