# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:12.
BEGIN attributes
  NAMES  rch32_stage_6
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000     151.80000000
    2841.00000000     151.80000000
END timeseries

