# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_119
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
    1643.00000000      -3.42907956
    1705.00000000      -6.95235228
    1826.00000000      -5.22680980
    2092.00000000      -7.41815988
    2192.00000000      -6.52002511
    2557.00000000      -6.28138604
    2586.00000000      -6.28138604
END timeseries

