# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_177
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
    2192.00000000      -5.84619001
    2223.00000000      -4.25637113
    2251.00000000      -4.17606632
    2282.00000000      -2.58790941
    2312.00000000      -2.88296964
    2343.00000000      -5.30724831
    2586.00000000      -5.30724831
END timeseries

