# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:13.
BEGIN attributes
  NAMES  pw_212p3
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000       0.00000000
     365.00000000      -0.00000000
     396.00000000      -0.03237180
     425.00000000      -0.00000000
     517.00000000      -2.39389443
     547.00000000      -0.00000000
     943.00000000      -0.19684141
     974.00000000      -0.00000000
    2586.00000000      -0.00000000
END timeseries

