# File generated by Flopy version 3.3.5 on 12/08/2022 at 08:55:14.
BEGIN attributes
  NAMES  pw_88
  METHODS  STEPWISE
END attributes

BEGIN timeseries
       0.00000000      -0.00838092
     365.00000000      -0.01671604
     731.00000000      -0.02095229
    1096.00000000      -0.01676184
    1461.00000000      -0.00000000
    1826.00000000      -1.49078229
    2586.00000000      -1.49078229
END timeseries

